//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TV_Tracers.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TV_TRACERS_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_DISPENSERTYPE               129
#define IDR_TV_TRAC_DATA                131
#define IDR_TV_TRAC_ACOUNT              132
#define IDD_HARDWARE_SETUP              134
#define IDD_PAGE_SETUP                  135
#define IDD_TV_TRACERS_FORM_SMAL        138
#define IDD_DEVICE_SETUP                139
#define IDD_NEW_NAME                    140
#define IDD_PROGRAM_DEVICES             141
#define IDD_NEW_LENGHT                  142
#define IDD_LIMIT_SETUP                 143
#define IDD_SELECT_OPERATOR             144
#define IDB_BITMAP_VAHS                 145
#define IDD_PC_NUMBER                   146
#define IDD_OPERATORS_SETUP             147
#define IDD_NEW_OPERATOR                163
#define IDD_CONNECT_SETINGS             223
#define IDB_BITMAP_VAHS1                224
#define IDD_WPAN_SETUP                  226
#define IDD_TIMERS_SETUP                227
#define IDD_ROUTER_TIMERS_SETUP         228
#define IDD_LAMP_SETUP                  229
#define IDD_DIALOG_DISBLED_LAMPS        230
#define IDD_LAMP_GROUPS                 231
#define IDD_LAMP_IN_ROUTER_SETUP        232
#define IDD_ROUTER_SELECT               233
#define IDD_TYPE_LAMP_SETUP             234
#define IDD_ENRGY_METERS                235
#define IDD_DATE_TIME_LIMIT             236
#define IDD_AUTO_ON_OFF                 237
#define IDC_CURRENT_POS                 1001
#define IDC_STATUS                      1002
#define IDC_VERSION                     1003
#define IDC_BUTTON_UP_SLOW              1004
#define IDC_ERR_PULSES                  1005
#define IDC_CURRENT_PULSES              1006
#define IDC_AC_STATUS                   1007
#define IDC_AC_RPM                      1008
#define IDC_AC_CURRENT                  1009
#define IDC_AC_HERC                     1010
#define IDC_DAC                         1011
#define IDC_DC                          1012
#define IDC_VDD                         1013
#define IDC_50Hz                        1014
#define IDC_HARDWARE_LIMITS             1015
#define IDC_LOCAL_MOVS                  1016
#define IDC_AC_READY                    1017
#define IDC_EDIT_CONFIRM_PASSWORD       1018
#define IDC_BUTTON_DOWN_SLOW            1019
#define IDC_BUTTON_UP_FAST              1020
#define IDC_BUTTON_DOWN_FAST            1021
#define IDC_BUTTON_REPER                1022
#define IDC_EDIT_POSITION               1023
#define IDC_HELP1                       1024
#define IDC_BUTTON_POSITION             1025
#define IDC_STOP                        1026
#define IDC_PROG_DEVICE                 1027
#define IDC_BUTTON_PRINT_PREVIEV        1028
#define IDC_OFFSET                      1029
#define IDC_BUTTON_PRINT                1030
#define IDC_HELP2                       1031
#define IDC_GRID                        1032
#define IDC_MIN                         1033
#define IDC_BUTTON_NEW                  1034
#define IDC_MAX                         1035
#define IDC_BUTTON_DEL                  1036
#define IDC_IPADDRESS1                  1037
#define IDC_BUTTON_COLOR                1038
#define IDC_CHECK_COM                   1039
#define IDC_BUTTON_COLOR_TEXT           1040
#define IDC_EDIT_COM                    1041
#define IDC_EDIT_NAME                   1042
#define IDC_RADIO_ADR0                  1043
#define IDC_RADIO_ADR1                  1044
#define IDC_RADIO_ADR2                  1045
#define IDC_RADIO_ADR3                  1046
#define IDC_RADIO_ADR4                  1047
#define IDC_RADIO_ADR5                  1048
#define IDC_RADIO_ADR6                  1049
#define IDC_RADIO_ADR7                  1050
#define IDC_RADIO_ADR8                  1051
#define IDC_RADIO_ADR9                  1052
#define IDC_RADIO_ADR10                 1053
#define IDC_RADIO_ADR11                 1054
#define IDC_RADIO_ADR12                 1055
#define IDC_RADIO_ADR13                 1056
#define IDC_RADIO_ADR14                 1057
#define IDC_BUTTON_TEST                 1057
#define IDC_RADIO_ADR15                 1058
#define IDC_BUTTON_LOAD                 1058
#define IDC_RADIO_ADR16                 1059
#define IDC_BUTTON_ON                   1059
#define IDC_BUTTON_LOAD_ROUTERS         1059
#define IDC_RADIO_ADR17                 1060
#define IDC_BUTTON_OFF                  1060
#define IDC_BUTTON_LOAD_ROUTERS_REJECT  1060
#define IDC_RADIO_ADR18                 1061
#define IDC_BUTTON_TIME                 1061
#define IDC_RADIO_ADR19                 1062
#define IDC_BUTTON_LIGHT                1062
#define IDC_RADIO_ADR20                 1063
#define IDC_BUTTON_TEST1                1063
#define IDC_RADIO_ADR21                 1064
#define IDC_BUTTON_ON1                  1064
#define IDC_RADIO_ADR22                 1065
#define IDC_BUTTON_OFF1                 1065
#define IDC_RADIO_ADR23                 1066
#define IDC_BUTTON_TIME1                1066
#define IDC_RADIO_ADR24                 1067
#define IDC_BUTTON_LIGHT1               1067
#define IDC_RADIO_ADR25                 1068
#define IDC_EDIT_LIGHTS                 1068
#define IDC_RADIO_ADR26                 1069
#define IDC_EDIT_ON_HOUR                1069
#define IDC_RADIO_ADR27                 1070
#define IDC_EDIT_ON_MINUTE              1070
#define IDC_BUTTON_SET1                 1070
#define IDC_RADIO_ADR28                 1071
#define IDC_EDIT_OFF_HOUR               1071
#define IDC_BUTTON_GET1                 1071
#define IDC_RADIO_ADR29                 1072
#define IDC_EDIT_OFF_MINUTE             1072
#define IDC_BUTTON_GET_MAC1             1072
#define IDC_EDIT1                       1072
#define IDC_RADIO_ADR30                 1073
#define IDC_BUTTON_SET                  1073
#define ID_SAVE_DATA                    1073
#define IDC_RADIO_ADR31                 1074
#define IDC_BUTTON_GET                  1074
#define IDC_STATIC_SUCSES               1074
#define IDC_TEXT_STATUS                 1075
#define IDC_BUTTON_GET_MAC              1075
#define IDC_DB_GROUP1                   1075
#define IDC_NAME_DEVICE                 1076
#define IDC_BUTTON_GET_REJECT1          1076
#define IDC_DB_GROUP2                   1076
#define IDC_LED                         1077
#define IDC_BUTTON_LAMPS_SET1           1077
#define IDC_DB_GROUP3                   1077
#define IDC_LED_SELECT                  1078
#define IDC_BUTTON_LAMPS_SET            1078
#define IDC_DB_GROUP4                   1078
#define IDC_BUTTON_ONE                  1079
#define IDC_BUTTON_GET_LANPS_STATUS1    1079
#define IDC_DB_GROUP5                   1079
#define IDC_BUTTON_ALL                  1080
#define IDC_BUTTON_GET_LANPS_STATUS     1080
#define IDC_DB_GROUP6                   1080
#define IDC_BUTTON_REFRESH              1081
#define IDC_BUTTON_GET_REJECT           1081
#define IDC_DB_GROUP7                   1081
#define IDC_POSITION                    1082
#define IDC_BUTTON_CLEAR_RAM1           1082
#define IDC_DB_GROUP8                   1082
#define IDC_STORED_POSITION             1083
#define IDC_BUTTON_CLEAR_RAM            1083
#define IDC_DB_GROUP9                   1083
#define IDC_COMBO_NAME                  1084
#define IDC_DB_GROUP10                  1084
#define IDC_EDIT_PASSWORD               1085
#define IDC_DB_GROUP11                  1085
#define IDC_EDIT_NUMBER                 1086
#define IDC_DB_GROUP12                  1086
#define IDC_DB_GROUP13                  1087
#define IDC_STATIC_VERSION_DB           1088
#define IDC_DB_GROUP14                  1088
#define IDC_STATIC_VERSION              1089
#define IDC_DB_GROUP15                  1089
#define IDC_EDIT_PASSORD                1090
#define IDC_DB_GROUP16                  1090
#define IDC_EDIT_LEFT                   1091
#define IDC_BUTTON_LOAD_DB              1091
#define IDC_EDIT_TOP                    1092
#define IDC_BUTTON_SAVE_DB              1092
#define IDC_EDIT_RIGHT                  1093
#define IDC_BUTTON_LOAD_LAMP            1093
#define IDC_EDIT_BOTTOM                 1094
#define IDC_BUTTON_SAVE_LAMP            1094
#define IDC_CHECK_FIT_PAGE              1095
#define IDC_BLACK_WITE                  1096
#define IDC_COMBO2                      1201
#define IDC_LAT                         1202
#define IDC_LON                         1203
#define IDC_CALCULATE                   1204
#define IDC_SUNRISE                     1205
#define IDC_SUNSET                      1206
#define IDC_BUTTON_CURRENT1             1206
#define IDC_BUTTON_CURRENT              1207
#define IDC_OFFSET_ONOFF                1207
#define IDC_BUTTON_TOTAL1               1208
#define IDC_BUTTON_TOTAL                1209
#define IDC_BUTTON_GET_HISTORY          1210
#define IDC_SUNRISEOFFSET               1210
#define IDC_BUTTON_HISTORY1             1211
#define IDC_SUNSET_OFFSET               1211
#define IDC_DATE_MIN                    1212
#define IDC_DATE_MAX                    1213
#define IDC_CHECK_AUTO_ONOFF            1213
#define IDC_TIME_MIN                    1214
#define IDC_TIME_MAX                    1215
#define IDS_ANOTHER_TRAKERS             4592
#define IDS_PAGE_OF_PAGE                4593
#define IDS_FILE_SAVE_AS_TEXT           4594
#define IDS_FILE_SAVE_AS_SAPSAN         4595
#define IDS_ERR_HARWARE_UNKNOWN         4596
#define IDS_ERR_HARWARE_NOT_PRESENT     4597
#define IDS_ERR_HARWARE_IS_BUSY         4598
#define IDS_ERR_HARWARE_MORE_PROTOCOLS  4599
#define IDS_SOCKET_ERR                  4600
#define IDS_DEVICE_SETUP                4601
#define IDS_TEXT_EXIT                   4602
#define IDS_BUT_PRINT_PREVIEF           4603
#define IDS_BUT_PRINT                   4604
#define IDS_BUT_UPDATE                  4605
#define IDS_HARDWARE                    4606
#define IDS_DELETE                      4607
#define IDS_BUSY_IN_DEVICES             4608
#define IDS_HARDWARE_IS                 4609
#define IDS_TEST_VIEW                   4610
#define IDS_NO_TEST_VIEV                4611
#define IDS_NO_DATA                     4612
#define IDS_FULL_TEST                   4613
#define IDS_STOP                        4614
#define IDS_WORK                        4615
#define IDS_NO_WORK                     4616
#define IDS_NAME_IS                     4617
#define IDS_BUSY_IN_ACCOUNT             4618
#define IDS_ADDRESS                     4619
#define IDS_DEVICE                      4620
#define IDS_NO_CONNECT                  4621
#define IDS_PROGRAM_OK                  4622
#define IDS_PROGRAM_ERR                 4623
#define IDS_AC_ERR                      4624
#define IDS_AC_OK                       4625
#define IDS_LIMIT_UP                    4626
#define IDS_LIMIT_DOWN                  4627
#define IDS_LIMIT_SOFT                  4628
#define IDS_LIMIT_NO                    4629
#define IDS_ERR_VAGE                    4630
#define IDS_LOCAL_UP                    4631
#define IDS_LOCAL_DOWN                  4632
#define IDS_LOCAL_NO                    4633
#define IDS_MOVE_UP                     4634
#define IDS_MOVE_DOWN                   4635
#define IDS_VERSION                     4636
#define IDS_SUCSES                      4637
#define IDS_HELP1                       4638
#define IDS_HELP2                       4639
#define IDS_NAME                        4640
#define IDS_CLEAR_RAM                   4641
#define IDS_OFFSET                      4642
#define IDS_MIN                         4643
#define IDS_MAX                         4644
#define IDS_LIMITS                      4645
#define IDS_ERR_REMAK                   4646
#define IDS_NO_SCENE                    4647
#define IDS_SAVE_TRACERS                4648
#define IDS_NO_DEVICE                   4649
#define IDS_UNTITLED                    4650
#define IDS_UNKNOV_DATA_BASE            4651
#define IDS_NOT_OPERATOR                4652
#define IDS_NOT_OPERATORS_INF           4653
#define IDS_NOT_PASSWORD                4654
#define IDS_UNKNOW_OPERATOR_NAME        4655
#define IDS_PRIVILEGI                   4656
#define IDS_SERVIZ                      4657
#define IDS_ADMIN                       4658
#define IDS_OPER                        4659
#define IDS_CURRENT_OPERATOR            4660
#define IDS_NOT_CONFIRM_PASSWORD        4661
#define IDS_NOT_PASSWORD_ADD            4662
#define IDS_NOT_NAME                    4663
#define IDS_SYSTEM_ACCOUNT_NAME1        4664
#define IDS_OPERATOR                    4665
#define IDS_DATETIME                    4666
#define IDS_SYSTEM_TYPE                 4667
#define IDS_SYSTEM_UNKNOW               4668
#define IDS_CONFIG_DEVICES              4669
#define IDS_CONFIG_LAMPS                4669
#define IDS_CONFIG_OPERATORS            4670
#define IDS_CONFIG_HARDWARE             4671
#define IDS_CONFIG_ROUTERS              4671
#define IDS_CONFIG_LIMITS               4672
#define IDS_CONFIG_PC_NUMBER            4673
#define IDS_CONFIG_CONNECT              4674
#define IDS_SYSTEM_ACCOUNT_NAME         4675
#define IDS_NUMBER_PC                   4676
#define IDS_DEVICE_ACCOUNT_NAME1        4677
#define IDS_DEVICE_ACCOUNT_NAME         4678
#define IDS_METRI                       4679
#define IDS_DEVICE_TYPE                 4680
#define IDS_NONE                        4681
#define IDS_MOVE_UP_FAST                4682
#define IDS_MOVE_DOWN_FAST              4683
#define IDS_GO_REPER                    4684
#define IDS_GO_POS                      4685
#define IDS_DELETE_ACCOUTS              4686
#define IDS_CLEAR_ACCOUNTS              4687
#define IDS_DECORI                      4688
#define IDS_SOCKETS_INIT_FAILED         4689
#define IDS_LIMIT_ERR                   4690
#define IDS_ERROR                       4690
#define IDS_Q10                         4691
#define IDS_ADDRESS1                    4691
#define IDS_OVERLOAD                    4692
#define IDS_ADDRESS2                    4692
#define IDS_MOVE_LEFT                   4693
#define IDS_GPRS_ERRORS                 4693
#define IDS_MOVE_RIGHT                  4694
#define IDS_ON_OFF                      4694
#define IDS_LIMIT_LEFT                  4695
#define IDS_NUMBER                      4695
#define IDS_LIMIT_RIGHT                 4696
#define IDS_CHANNEL                     4696
#define IDS_NO_LEFT_RIGHT               4697
#define IDS_PAN_ID                      4697
#define IDS_SEQURITY                    4698
#define IDS_MAC_ADDRESS                 4699
#define IDS_ON_OFF_POWER                4700
#define IDS_ON                          4701
#define IDS_OFF                         4702
#define IDS_LIGHT                       4703
#define IDS_GROUP                       4704
#define IDS_BUSY_IN_RUTERS              4705
#define IDS_TIMERS                      4706
#define IDS_RADIUS                      4707
#define IDS_LAMPS                       4708
#define IDS_LAMPS_CONNECTED             4709
#define IDS_REJECTED                    4710
#define IDS_ROUTER                      4711
#define IDS_LAST_CONTACT                4712
#define IDS_WORK_HOURS                  4713
#define IDS_STREET                      4714
#define IDS_STREET_NUMBER               4715
#define IDS_STREET_LAMPS                4716
#define IDS_DIABLED_LAMP_L1             4717
#define IDS_DIABLED_LAMP_L2             4718
#define IDS_FILE_SAVE_AS                4719
#define IDS_LAST_TEST                   4720
#define IDS_PERCENT_CONNECTED           4721
#define IDS_NUMBER_IS_BUSY              4722
#define IDS_BAD_MAC                     4723
#define IDS_GROUPS                      4724
#define IDS_NO_RUTER                    4725
#define IDS_NO_HARDWARE                 4726
#define IDS_NO_LAMP                     4727
#define IDS_TIME_ON_ROUTER              4728
#define IDS_TIME_OFF_ROUTER             4729
#define IDS_CSQ                         4730
#define IDS_STATE                       4731
#define IDS_RELAY                       4732
#define IDS_TIME_ON                     4733
#define IDS_TIME_OFF                    4734
#define IDS_TEST_LQI1                   4735
#define IDS_TEST_LQI                    4736
#define IDS_LQI                         4737
#define IDS_PER                         4738
#define IDS_PARENT                      4739
#define IDS_CHILDREN                    4740
#define IDS_DEPTH                       4741
#define IDS_LAT                         4742
#define IDS_LNG                         4743
#define IDS_TYPE_LAMP                   4744
#define IDS_LABEL                       4745
#define IDS_ON_OFF_POWER2               4746
#define IDS_MY_IP                       4747
#define IDS_CONFIG_ENERGY_METERS        5000
#define IDS_CURRENT_ENERGY              5001
#define IDS_CURRENT_ENERGY1             5002
#define IDS_CURRENT_ENERGY2             5003
#define IDS_CURRENT_ENERGY3             5004
#define IDS_CURRENT_ENERGY4             5005
#define IDS_CURRENT_ENERGY5             5006
#define IDS_CURRENT_ENERGY6             5007
#define IDS_CURRENT_ENERGY7             5008
#define IDS_CURRENT_ENERGY_NAME         5009
#define IDS_CURRENT_ENERGY_FILE         5010
#define IDS_TOTAL_CALCULATED            5011
#define IDS_CURRENT_ENERGY8             5012
#define IDS_CURRENT_ENERGY9             5013
#define IDS_CURRENT_ENERGY10            5014
#define IDS_TOTAL_ENERGY                5020
#define IDS_TOTAL_ENERGY1               5021
#define IDS_TOTAL_ENERGY2               5022
#define IDS_TOTAL_ENERGY3               5023
#define IDS_TOTAL_ENERGY4               5024
#define IDS_TOTAL_ENERGY_NAME           5028
#define IDS_TOTAL_ENERGY_FILE           5029
#define IDS_HISTORY_ENERGY              5030
#define IDS_HISTORY_ENERGY1             5031
#define IDS_HISTORY_ENERGY2             5032
#define IDS_CURRENT_ENRGY26             5033
#define IDS_CURRENT_ENRGY27             5034
#define IDS_CURRENT_ENRGY28             5035
#define IDS_CURRENT_ENRGY29             5036
#define IDS_CURRENT_ENRGY30             5037
#define IDS_HISTORY_ENERGY_NAME         5038
#define IDS_HISTORY_ENERGY_FILE         5039
#define IDS_TOTAL                       5040
#define IDS_RESER_SIM                   5041
#define IDS_HOST_VERSION                5042
#define IDS_JENNIC_VERSION              5043
#define IDS_POWER_W                     5044
#define IDS_WPAN                        5045
#define IDS_RESET_GPRS                  5046
#define IDS_HOUR                        5047
#define IDS_MINUTE                      5048
#define IDS_ENERGY_METER                5049
#define ID_FILE_PAGESETUP               32771
#define ID_DEVICE_SETUP                 32772
#define ID_STOP_ALL                     32773
#define ID_PROGRAM_DEVICES              32774
#define ID_SELECT_ALL                   32775
#define ID_SELECT_DEVICE                32776
#define ID_MOVE_UP_SLOW                 32777
#define ID_MOVE_UP_FAST                 32778
#define ID_MOVE_DOWN_FAST               32779
#define ID_MOVE_DOWN_SLOW               32780
#define ID_REPER                        32781
#define ID_IN_POSITION                  32782
#define ID_IN_OFFSET_POSITION           32783
#define ID_ENABLE_MOVE                  32787
#define ID_REPER_ALL                    32788
#define ID_GO_DOWN_ALL                  32790
#define ID_SELECT                       32791
#define ID_DESELECT                     32792
#define ID_IN_STORED_ONE                32793
#define ID_IN_STORED_ALL                32797
#define ID_SELECT_OPERATOR              32798
#define ID_COBFIG_OPERATOR              32799
#define ID_SELECT_PC                    32800
#define ID_CONFIG_DB                    32801
#define ID_ACCOUNTS_SYSTEM              32802
#define ID_ACCOUNTS_DEVICES             32803
#define ID_ACCOUNTS_ONE_DEVICE          32804
#define ID_ACCOUNTS_CLEAR               32805
#define ID_GO_UP_ALL                    32806
#define ID_DESELECT_ALL                 32807
#define ID_CHANGE_DECORY                32808
#define ID_LAMPS_SETUP                  32809
#define ID_TEST_LQI                     32811
#define ID_INDICATOR_SO                 0xE705
#define IDS_INDICATOR_LIM               59142
#define ID_INDICATOR_LIM                0xE707

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1214
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
